language: node_js
notifications:
  slack: ifhexas1:5F8LnMG9s1X6zYnxrFaz9FZw
  email:
    on_success: never
    on_failure: change
node_js:
- stable
before_install:
- npm install -g typings gulp-cli npm@4
script:
- npm test
