#Tout récupérer sur un Manga
select distinct ?p ?o  where {
  values ?resource {dbr:Doraemon}.
  ?resource rdf:type dbo:Manga.
  ?resource ?p ?o.
}

#Tout récupérer sur un auteur
select distinct ?p ?o   where {
  values ?resource {dbr:Eiichiro_Oda}.
  ?resource dbo:occupation ?o.
}

#Tout récupérer sur un auteur
select distinct ?p ?o   where {
  values ?resource {dbr:Eiichiro_Oda}.
  ?manga predicatAuteur ?resource
  ?manga a dbo:Manga
}
